### ISSUE TITLE
HomeAssistant Integration

### ISSUE THREAD

**Issue by sebastiantheobald** [LeonardSchwenk/public-gruppenadressen-generator#10]
Generierung der benötigten Konfigurationsfile für die HomeAssistant KNX Integration.

Dokumentation:

https://www.home-assistant.io/integrations/knx/

output wäre eine YAML

```yml
# Example configuration.yaml entry
knx:
  expose:
    - type: temperature
      entity_id: sensor.owm_temperature
      address: "0/0/2"
      cooldown: 600
    - type: string
      address: "0/6/4"
      entity_id: sensor.owm_weather
    - type: binary
      entity_id: binary_sensor.kitchen_window
      address: "0/6/5"
    - type: binary
      entity_id: light.office
      address: "0/3/0"
      default: false
    - type: percentU8
      entity_id: light.office
      attribute: brightness
      default: 0
      address: "0/3/1"
    - type: time
      address: "0/0/1"
    - type: datetime
      address: "0/0/23"
```
